# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='image',
            name='ordering',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordering'),
        ),
    ]
