# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20170108_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['gallery', 'ordering', '-id'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
