# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Modified')),
                ('user_id', models.PositiveIntegerField(verbose_name='User id')),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
    ]
