# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lead_text',
            field=models.TextField(default='lead text', verbose_name='Lead Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='user_id',
            field=models.PositiveIntegerField(verbose_name='User ID'),
        ),
    ]
