# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('OR', 'Ordered'), ('PR', 'Processed'), ('SH', 'Shipped')], default='IP', max_length=2)),
                ('finished_on', models.DateTimeField(blank=True, null=True, verbose_name='Finished on')),
                ('shipped_on', models.DateTimeField(blank=True, null=True, verbose_name='Shipped on')),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('place', models.CharField(max_length=200, verbose_name='Place')),
                ('postal_code', models.IntegerField(verbose_name='Postal Code')),
                ('street', models.CharField(max_length=250, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, max_length=25, null=True, verbose_name='House Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
    ]
