# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.IntegerField(verbose_name='Phone Number'),
        ),
    ]
