# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 09:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20161109_1027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Shop Order'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='shopping_cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ShoppingCart', verbose_name='Shopping Cart'),
        ),
    ]
