# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-04 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20161204_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Ordered'),
        ),
    ]
